// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9YTOpcP6SU_bMnLA6wp84PeSat-zY13k',
    appId: '1:138873088366:web:042d8b67c768435f2f797f',
    messagingSenderId: '138873088366',
    projectId: 'crudefirebase-207d2',
    authDomain: 'crudefirebase-207d2.firebaseapp.com',
    storageBucket: 'crudefirebase-207d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVkm8sB5a78iIsGxYUhAIQN4-SaCZKKQ0',
    appId: '1:138873088366:android:7911069b82bee2f32f797f',
    messagingSenderId: '138873088366',
    projectId: 'crudefirebase-207d2',
    storageBucket: 'crudefirebase-207d2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9YTOpcP6SU_bMnLA6wp84PeSat-zY13k',
    appId: '1:138873088366:web:fa46c4d373b8d0a82f797f',
    messagingSenderId: '138873088366',
    projectId: 'crudefirebase-207d2',
    authDomain: 'crudefirebase-207d2.firebaseapp.com',
    storageBucket: 'crudefirebase-207d2.firebasestorage.app',
  );
}
